import { useState } from 'react';
import { useLanguage } from '../contexts/LanguageContext';
import { Lightbulb, Sprout, ChevronDown, ChevronUp } from 'lucide-react';

type TipItem = {
  key: string;
  category: 'field' | 'fruit' | 'flower';
  sowing: { en: string; te: string };
  irrigation: { en: string; te: string };
  fertilizer: { en: string; te: string };
  protection: { en: string; te: string };
};

const TIP_DATA: TipItem[] = [
  { key: 'rice', category: 'field', sowing: { en: 'Nursery in June-July; transplant 20-25 day seedlings.', te: 'జూన్-జూలైలో నర్సరీ వేసి 20-25 రోజుల మొక్కలు నాటండి.' }, irrigation: { en: 'Maintain 2-5 cm standing water until grain filling.', te: 'ధాన్యం ఏర్పడే వరకు 2-5 సెం.మీ నీటి మట్టం ఉంచండి.' }, fertilizer: { en: 'Apply NPK in 3 splits with zinc sulfate in zinc-deficient soils.', te: 'ఎన్‌పికెను 3 విడతలుగా వేసి జింక్ లోపం ఉన్న నేలల్లో జింక్ సల్ఫేట్ ఇవ్వండి.' }, protection: { en: 'Scout for stem borer and blast; spray only after threshold.', te: 'స్టెమ్ బోరర్, బ్లాస్ట్ పరిశీలించి పరిమితి దాటితేనే పిచికారీ చేయండి.' } },
  { key: 'wheat', category: 'field', sowing: { en: 'Sow in November with line spacing of 20 cm.', te: 'నవంబర్‌లో 20 సెం.మీ వరుస దూరంతో విత్తనం వేయండి.' }, irrigation: { en: 'Critical irrigations at CRI, tillering, flowering, and grain filling.', te: 'CRI, టిల్లరింగ్, పుష్ప దశ, గింజ నింపే దశల్లో నీరు ఇవ్వండి.' }, fertilizer: { en: 'Use balanced N:P:K and avoid excessive nitrogen after heading.', te: 'సమతుల్య ఎన్‌పికె వాడి హెడ్డింగ్ తర్వాత అధిక నత్రజని ఇవ్వవద్దు.' }, protection: { en: 'Monitor rust and aphids weekly during cool humid weather.', te: 'చల్లటి తేమ వాతావరణంలో తుప్పు తెగులు, ఆఫిడ్స్‌ను వారానికి ఒకసారి పరిశీలించండి.' } },
  { key: 'cotton', category: 'field', sowing: { en: 'Use Bt hybrid suited to local region and sow with seed treatment.', te: 'ప్రాంతానుకూల Bt హైబ్రిడ్‌ను విత్తన శుద్ధితో విత్తండి.' }, irrigation: { en: 'Adopt drip with mulching for water efficiency.', te: 'నీటి పొదుపు కోసం డ్రిప్ మరియు మల్చింగ్ అనుసరించండి.' }, fertilizer: { en: 'Split nitrogen through fertigation and add boron at square stage.', te: 'నత్రజనిని విడతలుగా ఫర్టిగేషన్ ద్వారా ఇచ్చి స్క్వేర్ దశలో బోరాన్ ఇవ్వండి.' }, protection: { en: 'Use pheromone traps for pink bollworm and rotate insecticides.', te: 'పింక్ బోల్‌వార్మ్ కోసం ఫెరోమోన్ ట్రాప్స్ వాడి పురుగుమందులను మారుస్తూ వాడండి.' } },
  { key: 'sugarcane', category: 'field', sowing: { en: 'Plant healthy 3-bud setts in furrows with trash mulching.', te: 'ఆరోగ్యకరమైన 3 కళ్ల కాండ ముక్కలను బుగ్గలలో నాటి ట్రాష్ మల్చింగ్ చేయండి.' }, irrigation: { en: 'Irrigate at 7-10 day interval in summer; reduce in rainy season.', te: 'వేసవిలో 7-10 రోజులకొకసారి, వర్షాకాలంలో అవసరానికి తగ్గట్టు నీరు ఇవ్వండి.' }, fertilizer: { en: 'Apply farmyard manure plus recommended NPK with micronutrients.', te: 'పశువుల ఎరువు తో పాటు సూచించిన ఎన్‌పికె మరియు సూక్ష్మపోషకాలు ఇవ్వండి.' }, protection: { en: 'Control early shoot borer using timely earthing up and traps.', te: 'సకాలంలో ఎర్తింగ్ అప్ చేసి ట్రాప్స్ ద్వారా ఎర్లీ షూట్ బోరర్‌ను నియంత్రించండి.' } },
  { key: 'maize', category: 'field', sowing: { en: 'Use single cross hybrid and maintain proper plant population.', te: 'సింగిల్ క్రాస్ హైబ్రిడ్ వాడి సరైన మొక్కల సాంద్రత ఉంచండి.' }, irrigation: { en: 'Critical watering at knee-high, tasseling and grain filling.', te: 'నీ-హై, టాసెలింగ్ మరియు గ్రెయిన్ ఫిల్లింగ్ దశల్లో నీరు తప్పనిసరి.' }, fertilizer: { en: 'Side-dress nitrogen at 25 and 45 DAS.', te: '25 మరియు 45 రోజులకు నత్రజని సైడ్ డ్రెస్సింగ్ చేయండి.' }, protection: { en: 'Monitor fall armyworm in whorl stage; deploy pheromone traps.', te: 'వోర్ల్ దశలో ఫాల్ ఆర్మీవార్మ్ గమనించి ఫెరోమోన్ ట్రాప్స్ వాడండి.' } },
  { key: 'chilli', category: 'field', sowing: { en: 'Raise healthy nursery and transplant in well-drained beds.', te: 'ఆరోగ్యకర నర్సరీ పెంచి నీరు నిల్వ లేకుండా ఉండే పడకల్లో నాటండి.' }, irrigation: { en: 'Light and frequent irrigation; avoid waterlogging.', te: 'తక్కువ మోతాదులో తరచుగా నీరు ఇవ్వండి, నిల్వ నీరు ఉండనివ్వవద్దు.' }, fertilizer: { en: 'Use calcium and boron sprays during flowering.', te: 'పుష్ప దశలో కాల్షియం, బోరాన్ స్ప్రేలు వాడండి.' }, protection: { en: 'Manage thrips and mites with sticky traps and need-based sprays.', te: 'త్రిప్స్, మైట్స్ కోసం స్టిక్కీ ట్రాప్స్ మరియు అవసరమైనప్పుడు స్ప్రే చేయండి.' } },
  { key: 'tomato', category: 'field', sowing: { en: 'Use disease-free seedlings and stake plants early.', te: 'రోగరహిత మొక్కలు నాటి ముందుగానే స్టేకింగ్ చేయండి.' }, irrigation: { en: 'Maintain uniform moisture to avoid fruit cracking.', te: 'పండ్లు చిట్లకుండా సమాన తేమను కొనసాగించండి.' }, fertilizer: { en: 'Foliar spray of calcium nitrate at fruit set.', te: 'ఫ్రూట్ సెటింగ్ దశలో కాల్షియం నైట్రేట్ ఆకుపై పిచికారీ చేయండి.' }, protection: { en: 'Scout for leaf curl vectors and remove infected plants quickly.', te: 'లీఫ్ కర్ల్ వ్యాధి వాహకాలను పరిశీలించి సోకిన మొక్కలు తొలగించండి.' } },
  { key: 'potato', category: 'field', sowing: { en: 'Plant certified seed tubers at 45x20 cm spacing.', te: 'సర్టిఫైడ్ గింజ కందలను 45x20 సెం.మీ దూరంతో నాటండి.' }, irrigation: { en: 'Irrigate lightly after planting and at tuber initiation.', te: 'నాటిన తర్వాత తేలికగా, కంద ఏర్పాటులో సకాలంలో నీరు ఇవ్వండి.' }, fertilizer: { en: 'Higher potash improves tuber quality and shelf life.', te: 'అధిక పొటాష్ కంద నాణ్యత, నిల్వ కాలాన్ని మెరుగుపరుస్తుంది.' }, protection: { en: 'Prevent late blight with weather-based fungicide schedule.', te: 'వాతావరణ సూచన ఆధారంగా లేట్ బ్లైట్ నివారణకు ఫంగిసైడ్ షెడ్యూల్ పాటించండి.' } },
  { key: 'onion', category: 'field', sowing: { en: 'Use healthy seedlings and transplant on raised beds.', te: 'ఆరోగ్యకరమైన మొక్కలు ఎత్తైన పడకల్లో నాటండి.' }, irrigation: { en: 'Frequent irrigation during bulb formation; stop before harvest.', te: 'బల్బ్ ఏర్పాటులో తరచుగా నీరు ఇచ్చి కోతకు ముందు ఆపండి.' }, fertilizer: { en: 'Apply sulfur and potassium for better bulb size.', te: 'బల్బ్ పరిమాణం కోసం సల్ఫర్, పొటాష్ ఇవ్వండి.' }, protection: { en: 'Manage thrips with blue sticky traps and neem-based spray.', te: 'త్రిప్స్ నియంత్రణకు నీలం స్టిక్కీ ట్రాప్స్, వేప ఆధారిత స్ప్రే వాడండి.' } },
  { key: 'groundnut', category: 'field', sowing: { en: 'Sow bold kernels after seed treatment with Trichoderma.', te: 'ట్రైకోడెర్మా శుద్ధి చేసిన పెద్ద గింజలను విత్తండి.' }, irrigation: { en: 'Critical irrigation at flowering and pegging stages.', te: 'పుష్ప దశ, పెగ్గింగ్ దశల్లో నీరు తప్పనిసరి.' }, fertilizer: { en: 'Gypsum at flowering improves pod filling.', te: 'పుష్ప దశలో జిప్సం ఇవ్వడం వల్ల పొట్ల నింపుదల మెరుగవుతుంది.' }, protection: { en: 'Watch for tikka leaf spot and apply fungicide in rotation.', te: 'టిక్కా లీఫ్ స్పాట్‌ను గమనించి ఫంగిసైడ్‌ను మారుస్తూ వాడండి.' } },
  { key: 'soybean', category: 'field', sowing: { en: 'Use Rhizobium inoculation before sowing.', te: 'విత్తనానికి ముందు రైజోబియం ఇనాక్యులేషన్ చేయండి.' }, irrigation: { en: 'Mostly rainfed; give lifesaving irrigation during dry spells.', te: 'సాధారణంగా వర్షాధార పంట; ఎండకాలంలో లైఫ్ సేవింగ్ నీరు ఇవ్వండి.' }, fertilizer: { en: 'Apply phosphorus and sulfur for better nodulation.', te: 'మంచి నాడ్యులేషన్ కోసం ఫాస్ఫరస్, సల్ఫర్ ఇవ్వండి.' }, protection: { en: 'Scout girdle beetle and semilooper; adopt IPM.', te: 'గర్డిల్ బీటిల్, సెమిలోపర్ కోసం ఐపీఎం పద్ధతులు అనుసరించండి.' } },
  { key: 'mustard', category: 'field', sowing: { en: 'Early sowing gives better branching and yield.', te: 'ముందుగా విత్తడం వల్ల శాఖలు, దిగుబడి మెరుగవుతాయి.' }, irrigation: { en: 'Irrigate at flowering and siliqua formation.', te: 'పుష్ప దశ, సిలిక్వా ఏర్పాటులో నీరు ఇవ్వండి.' }, fertilizer: { en: 'Apply sulfur-rich fertilizer for oil content improvement.', te: 'నూనె శాతం పెరగడానికి సల్ఫర్ అధికంగా ఉన్న ఎరువు వాడండి.' }, protection: { en: 'Control aphids using yellow sticky traps and neem extract.', te: 'ఆఫిడ్స్ నియంత్రణకు పసుపు స్టిక్కీ ట్రాప్స్, వేప సారం వాడండి.' } },
  { key: 'turmeric', category: 'field', sowing: { en: 'Plant healthy rhizomes with 45x20 cm spacing.', te: 'ఆరోగ్యకరమైన రైజోమ్‌లను 45x20 సెం.మీ దూరంతో నాటండి.' }, irrigation: { en: 'Keep soil moist, especially during rhizome bulking.', te: 'రైజోమ్ పెరుగుదల దశలో నేల తేమను నిలుపుకోండి.' }, fertilizer: { en: 'Heavy organic manure plus split NPK boosts yield.', te: 'అధిక సేంద్రియ ఎరువులు, విడతల ఎన్‌పికె వల్ల దిగుబడి పెరుగుతుంది.' }, protection: { en: 'Use clean seed and drench for rhizome rot prevention.', te: 'శుభ్రమైన విత్తనం వాడి రైజోమ్ రాట్ నివారణకు డ్రెంచింగ్ చేయండి.' } },
  { key: 'sunflower', category: 'field', sowing: { en: 'Sow in rows with optimum spacing for head size.', te: 'తల పరిమాణం కోసం సరైన దూరంతో వరుసల్లో విత్తండి.' }, irrigation: { en: 'Water at bud initiation and flowering stage.', te: 'బడింగ్, పుష్ప దశల్లో నీరు ఇవ్వండి.' }, fertilizer: { en: 'Boron spray prevents empty seeds in the head.', te: 'తలలో ఖాళీ గింజలు తగ్గించేందుకు బోరాన్ స్ప్రే వాడండి.' }, protection: { en: 'Bird perches and timely harvest reduce losses.', te: 'పక్షుల నష్టం తగ్గేందుకు బర్డ్ పెర్చ్‌లు, సకాలంలో కోత చేయండి.' } },
  { key: 'bengal_gram', category: 'field', sowing: { en: 'Sow after monsoon retreat in residual moisture soils.', te: 'వర్షాకాలం ముగిశాక మిగిలిన తేమ ఉన్న నేలల్లో విత్తండి.' }, irrigation: { en: 'Mostly rainfed; one irrigation at pod formation helps.', te: 'వర్షాధార పంట; పొట్ల దశలో ఒకసారి నీరు ఇస్తే మంచిది.' }, fertilizer: { en: 'Starter nitrogen with phosphorus is sufficient.', te: 'స్టార్టర్ నత్రజని మరియు ఫాస్ఫరస్ చాలును.' }, protection: { en: 'Monitor pod borer and install pheromone traps.', te: 'పాడ్ బోరర్ గమనించి ఫెరోమోన్ ట్రాప్స్ ఏర్పాటు చేయండి.' } },
  { key: 'red_gram', category: 'field', sowing: { en: 'Use short-duration varieties in intercropping systems.', te: 'ఇంటర్‌క్రాపింగ్‌లో చిన్నకాల రకాలు వాడండి.' }, irrigation: { en: 'Give protective irrigation during flowering stress.', te: 'పుష్ప దశలో ఒత్తిడి ఉంటే రక్షణాత్మక నీరు ఇవ్వండి.' }, fertilizer: { en: 'Apply phosphorus and biofertilizers at sowing.', te: 'విత్తే సమయంలో ఫాస్ఫరస్, బయోఫర్టిలైజర్లు ఇవ్వండి.' }, protection: { en: 'Pod borer management with trap crops and biocontrol.', te: 'పాడ్ బోరర్ నియంత్రణకు ట్రాప్ క్రాప్స్, బయోకంట్రోల్ వాడండి.' } },
  { key: 'black_gram', category: 'field', sowing: { en: 'Choose wilt-resistant variety and treat seeds.', te: 'విల్ట్ నిరోధక రకం ఎంచుకుని విత్తన శుద్ధి చేయండి.' }, irrigation: { en: 'Short duration crop; avoid excess irrigation.', te: 'చిన్నకాల పంట; అధిక నీరు ఇవ్వవద్దు.' }, fertilizer: { en: 'Basal phosphorus and sulfur improve nodulation.', te: 'బేసల్ ఫాస్ఫరస్, సల్ఫర్ నాడ్యులేషన్ మెరుగుపరుస్తాయి.' }, protection: { en: 'Keep field weed-free in first 30 days.', te: 'మొదటి 30 రోజులు కలుపు లేకుండా ఉంచండి.' } },
  { key: 'green_gram', category: 'field', sowing: { en: 'Use line sowing for easy interculture and weeding.', te: 'ఇంటర్‌కల్చర్, కలుపు నియంత్రణకు వరుసల్లో విత్తండి.' }, irrigation: { en: 'One irrigation at flowering if rainfall is low.', te: 'వర్షం తక్కువైతే పుష్ప దశలో ఒకసారి నీరు ఇవ్వండి.' }, fertilizer: { en: 'Use Rhizobium + PSB inoculation for better uptake.', te: 'పోషకాల గ్రహణం కోసం రైజోబియం + PSB ఇనాక్యులేషన్ చేయండి.' }, protection: { en: 'Avoid water stagnation to prevent root rot.', te: 'రూట్ రాట్ నివారణకు నీరు నిల్వ ఉండనివ్వవద్దు.' } },
  { key: 'jowar', category: 'field', sowing: { en: 'Use drought-tolerant hybrids in rainfed belts.', te: 'వర్షాధార ప్రాంతాల్లో ఎండనిరోధక హైబ్రిడ్‌లు వాడండి.' }, irrigation: { en: 'Irrigate at booting and flowering if moisture stress appears.', te: 'తేమ ఒత్తిడి ఉంటే బూటింగ్, పుష్ప దశల్లో నీరు ఇవ్వండి.' }, fertilizer: { en: 'Split nitrogen once at sowing and once at 30 DAS.', te: 'నత్రజనిని విత్తే సమయంలో, 30 రోజులకు విడతలుగా ఇవ్వండి.' }, protection: { en: 'Use bird perches and timely harvest for grain protection.', te: 'ధాన్య రక్షణకు బర్డ్ పెర్చ్‌లు, సకాలంలో కోత చేయండి.' } },
  { key: 'bajra', category: 'field', sowing: { en: 'Sow with onset of monsoon in light soils.', te: 'తేలికపాటి నేలల్లో వర్షాకాలం మొదట విత్తండి.' }, irrigation: { en: 'Usually rainfed; irrigation only during severe dry spell.', te: 'సాధారణంగా వర్షాధార; తీవ్రమైన ఎండలో మాత్రమే నీరు ఇవ్వండి.' }, fertilizer: { en: 'Apply nitrogen in two splits for better tillering.', te: 'మంచి టిల్లరింగ్ కోసం నత్రజనిని 2 విడతలుగా ఇవ్వండి.' }, protection: { en: 'Rogue out downy mildew infected plants early.', te: 'డౌనీ మిల్డ్యూ సోకిన మొక్కలను త్వరగా తొలగించండి.' } },
  { key: 'ragi', category: 'field', sowing: { en: 'Transplanting improves yield over broadcasting.', te: 'బ్రాడ్‌కాస్టింగ్ కంటే నాటడం ద్వారా దిగుబడి పెరుగుతుంది.' }, irrigation: { en: 'Maintain moisture during tillering and ear emergence.', te: 'టిల్లరింగ్, చెవి దశల్లో తేమను కొనసాగించండి.' }, fertilizer: { en: 'Apply farmyard manure plus moderate NPK.', te: 'పశువుల ఎరువు తో పాటు మితమైన ఎన్‌పికె ఇవ్వండి.' }, protection: { en: 'Use timely weeding in first 30-35 days.', te: 'మొదటి 30-35 రోజుల్లో సకాలంలో కలుపు తీసేయండి.' } },
  { key: 'mango', category: 'fruit', sowing: { en: 'Plant grafted saplings at 10x10 m spacing.', te: 'గ్రాఫ్టెడ్ మొక్కలను 10x10 మీటర్ల దూరంతో నాటండి.' }, irrigation: { en: 'Irrigate young plants weekly; reduce before flowering.', te: 'చిన్న మొక్కలకు వారానికి ఒకసారి నీరు ఇచ్చి పుష్ప దశకు ముందు తగ్గించండి.' }, fertilizer: { en: 'Apply FYM and NPK based on tree age every year.', te: 'మొక్క వయస్సు ఆధారంగా ప్రతి సంవత్సరం FYM మరియు ఎన్‌పికె ఇవ్వండి.' }, protection: { en: 'Control hopper and powdery mildew at panicle stage.', te: 'పానికిల్ దశలో హాపర్, బూజు తెగులు నియంత్రణ చేయండి.' } },
  { key: 'banana', category: 'fruit', sowing: { en: 'Use tissue culture plants in raised pits.', te: 'టిష్యూ కల్చర్ మొక్కలను ఎత్తైన గుంతల్లో నాటండి.' }, irrigation: { en: 'Drip irrigation with mulching is ideal.', te: 'డ్రిప్ నీటిపారుదలతో మల్చింగ్ ఉత్తమం.' }, fertilizer: { en: 'Apply potassium-rich schedule for bunch size.', te: 'గుత్తి పరిమాణం కోసం పొటాష్ అధికంగా ఉన్న షెడ్యూల్ వాడండి.' }, protection: { en: 'Desucker and remove diseased leaves regularly.', te: 'సక్కర్లు తొలగించి వ్యాధిగ్రస్త ఆకులను తరచూ తొలగించండి.' } },
  { key: 'guava', category: 'fruit', sowing: { en: 'Plant air-layered saplings in pits enriched with compost.', te: 'కంపోస్ట్‌తో నింపిన గుంతల్లో ఎయిర్ లేయర్డ్ మొక్కలు నాటండి.' }, irrigation: { en: 'Irrigate at 10-12 day intervals in summer.', te: 'వేసవిలో 10-12 రోజులకొకసారి నీరు ఇవ్వండి.' }, fertilizer: { en: 'Balanced NPK before monsoon and post-monsoon.', te: 'వర్షాకాలం ముందు, తర్వాత సమతుల్య ఎన్‌పికె ఇవ్వండి.' }, protection: { en: 'Fruit fly traps and orchard sanitation are mandatory.', te: 'ఫ్రూట్ ఫ్లై ట్రాప్స్, తోట పరిశుభ్రత తప్పనిసరి.' } },
  { key: 'papaya', category: 'fruit', sowing: { en: 'Use virus-tolerant hybrids and raised beds.', te: 'వైరస్ నిరోధక హైబ్రిడ్స్‌ను ఎత్తైన పడకల్లో నాటండి.' }, irrigation: { en: 'Light irrigation every 3-4 days in summer.', te: 'వేసవిలో ప్రతి 3-4 రోజులకు తేలికగా నీరు ఇవ్వండి.' }, fertilizer: { en: 'Monthly fertigation gives better fruit size.', te: 'నెలనెలా ఫర్టిగేషన్ వల్ల పండు పరిమాణం మెరుగవుతుంది.' }, protection: { en: 'Control papaya ring spot vectors using sticky traps.', te: 'పపాయ రింగ్‌స్పాట్ వ్యాధి వాహకాలను స్టిక్కీ ట్రాప్స్‌తో నియంత్రించండి.' } },
  { key: 'pomegranate', category: 'fruit', sowing: { en: 'Plant in well-drained soils and follow bahar treatment.', te: 'నీరు నిల్వలేని నేలల్లో నాటి బహార్ ట్రీట్మెంట్ పాటించండి.' }, irrigation: { en: 'Regulated deficit irrigation improves fruit quality.', te: 'నియంత్రిత నీరు వల్ల పండ్ల నాణ్యత మెరుగవుతుంది.' }, fertilizer: { en: 'Micronutrient sprays improve aril color and size.', te: 'సూక్ష్మపోషక స్ప్రేలు గింజ రంగు, పరిమాణం మెరుగుపరుస్తాయి.' }, protection: { en: 'Bag fruits to reduce borer and sunburn damage.', te: 'బోరర్, సన్‌బర్న్ నష్టం తగ్గించేందుకు పండ్లకు బ్యాగింగ్ చేయండి.' } },
  { key: 'lemon', category: 'fruit', sowing: { en: 'Use certified grafts and maintain basin around plant.', te: 'సర్టిఫైడ్ గ్రాఫ్ట్స్ వాడి మొక్క చుట్టూ బేసిన్ ఉంచండి.' }, irrigation: { en: 'Irrigate at 7-10 day interval in dry season.', te: 'ఎండకాలంలో 7-10 రోజులకొకసారి నీరు ఇవ్వండి.' }, fertilizer: { en: 'Apply NPK and magnesium in split doses.', te: 'ఎన్‌పికె మరియు మెగ్నీషియంను విడతలుగా ఇవ్వండి.' }, protection: { en: 'Manage citrus canker with copper-based sprays.', te: 'సిట్రస్ కాన్కర్ నియంత్రణకు కాపర్ ఆధారిత స్ప్రేలు వాడండి.' } },
  { key: 'rose', category: 'flower', sowing: { en: 'Plant grafts in raised beds with good sunlight.', te: 'మంచి సూర్యకాంతి ఉండే ఎత్తైన పడకల్లో గ్రాఫ్ట్ మొక్కలు నాటండి.' }, irrigation: { en: 'Light irrigation every 2-3 days based on season.', te: 'సీజన్‌ను బట్టి 2-3 రోజులకు తేలికగా నీరు ఇవ్వండి.' }, fertilizer: { en: 'Use balanced NPK and regular pruning for quality blooms.', te: 'నాణ్యమైన పూల కోసం సమతుల్య ఎన్‌పికె, నియమిత ప్రూనింగ్ చేయండి.' }, protection: { en: 'Control thrips and mites with neem oil rotation.', te: 'త్రిప్స్, మైట్స్ కోసం వేపనూనె రొటేషన్ స్ప్రే చేయండి.' } },
  { key: 'marigold', category: 'flower', sowing: { en: 'Transplant 25-day seedlings at 45x45 cm spacing.', te: '25 రోజుల మొక్కలను 45x45 సెం.మీ దూరంతో నాటండి.' }, irrigation: { en: 'Irrigate every 4-5 days in flowering stage.', te: 'పుష్ప దశలో 4-5 రోజులకు నీరు ఇవ్వండి.' }, fertilizer: { en: 'Top dress nitrogen at 30 and 50 DAT.', te: '30, 50 రోజులకు నత్రజని టాప్‌డ్రెస్ చేయండి.' }, protection: { en: 'Remove spent flowers for continuous blooming.', te: 'నిరంతర పుష్పణకు వాడిపోయిన పూలను తొలగించండి.' } },
  { key: 'jasmine', category: 'flower', sowing: { en: 'Plant rooted cuttings in pits enriched with FYM.', te: 'FYM తో నింపిన గుంతల్లో వేరు వచ్చిన కట్టింగ్‌లు నాటండి.' }, irrigation: { en: 'Irrigate twice a week in summer.', te: 'వేసవిలో వారానికి రెండుసార్లు నీరు ఇవ్వండి.' }, fertilizer: { en: 'Apply nitrogen after each pruning cycle.', te: 'ప్రతి ప్రూనింగ్ తర్వాత నత్రజని ఇవ్వండి.' }, protection: { en: 'Control budworm through regular field scouting.', te: 'బడ్వార్మ్ నియంత్రణకు తరచూ క్షేత్ర పరిశీలన చేయండి.' } },
  { key: 'chrysanthemum', category: 'flower', sowing: { en: 'Plant rooted suckers with pinching at 25 DAS.', te: 'వేర్లు వచ్చిన సక్కర్లు నాటి 25 రోజులకు పించింగ్ చేయండి.' }, irrigation: { en: 'Keep medium moisture, avoid overwatering.', te: 'మధ్యస్థ తేమ ఉంచి అధిక నీరు ఇవ్వవద్దు.' }, fertilizer: { en: 'Foliar micronutrients improve flower size and color.', te: 'సూక్ష్మపోషక ఆకుస్ప్రేలు పూల పరిమాణం, రంగు మెరుగుపరుస్తాయి.' }, protection: { en: 'Install sticky traps for aphid and whitefly.', te: 'ఆఫిడ్, వైట్ ఫ్లై కోసం స్టిక్కీ ట్రాప్స్ ఏర్పాటు చేయండి.' } },
  { key: 'tuberose', category: 'flower', sowing: { en: 'Plant healthy bulbs in ridges at proper spacing.', te: 'ఆరోగ్యకరమైన బల్బులను రిడ్జ్‌లలో సరైన దూరంతో నాటండి.' }, irrigation: { en: 'Irrigate weekly and ensure good drainage.', te: 'వారానికి ఒకసారి నీరు ఇచ్చి మంచి డ్రెయినేజీ ఉంచండి.' }, fertilizer: { en: 'Use compost + split nitrogen for continuous spikes.', te: 'నిరంతర స్పైక్స్ కోసం కంపోస్ట్ + విడతల నత్రజని ఇవ్వండి.' }, protection: { en: 'Control bud rot with preventive fungicide drench.', te: 'బడ్రాట్ నివారణకు ముందస్తు ఫంగిసైడ్ డ్రెంచ్ చేయండి.' } },
];

export function FarmingTips() {
  const { t, language } = useLanguage();
  const [expanded, setExpanded] = useState<string | null>(null);

  const labels = {
    sowing: language === 'te' ? 'విత్తడం/నాటడం' : 'Sowing/Planting',
    irrigation: language === 'te' ? 'నీటి నిర్వహణ' : 'Irrigation',
    fertilizer: language === 'te' ? 'ఎరువులు' : 'Fertilizer',
    protection: language === 'te' ? 'వ్యాధి/పురుగు నియంత్రణ' : 'Protection',
    total: language === 'te' ? 'మొత్తం పంటలు' : 'Total Crops',
  };

  return (
    <div className="container mx-auto p-4 max-w-4xl">
      <h1 className="text-3xl font-bold mb-6 flex items-center gap-2">
        <Lightbulb className="text-yellow-500" />
        {t('farming_tips')}
      </h1>

      <p className="mb-4 text-sm text-gray-600">{labels.total}: {TIP_DATA.length}</p>

      <div className="grid md:grid-cols-2 gap-4">
        {TIP_DATA.map((crop) => (
          <div key={crop.key} className="bg-white rounded-xl shadow-md overflow-hidden border border-yellow-50 hover:shadow-lg transition-all">
            <button 
              onClick={() => setExpanded(expanded === crop.key ? null : crop.key)}
              className="w-full flex items-center justify-between p-4 bg-yellow-50 text-yellow-900 font-bold hover:bg-yellow-100 transition-colors"
            >
              <div className="flex items-center gap-3">
                <Sprout size={20} className="text-green-600" />
                {t(crop.key)}
                <span className="rounded-full bg-white px-2 py-0.5 text-xs font-medium text-gray-600">
                  {crop.category}
                </span>
              </div>
              {expanded === crop.key ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
            </button>
            
            {expanded === crop.key && (
              <div className="p-4 bg-white space-y-3 animate-fade-in text-gray-700 text-sm">
                <p><strong>{labels.sowing}:</strong> {crop.sowing[language]}</p>
                <p><strong>{labels.irrigation}:</strong> {crop.irrigation[language]}</p>
                <p><strong>{labels.fertilizer}:</strong> {crop.fertilizer[language]}</p>
                <p><strong>{labels.protection}:</strong> {crop.protection[language]}</p>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}